# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17mfAVY0YtYjvgxpozVbmR61lgHOP2D2L
"""

import streamlit as st
import pandas as pd

# -----------------------------
# Page Config
# -----------------------------
st.set_page_config(
    page_title="Quick Overview of My Understanding",
    layout="wide"
)

# -----------------------------
# Helper Functions (MODULAR)
# -----------------------------

def credit_bureau_intro():
    st.header("Lending Industry Related Data")

    st.subheader("1️⃣ What is a Credit Bureau?")
    st.write("""
    A Credit Bureau is a regulated organization that collects, consolidates,
    and provides credit behavior data of borrowers across multiple lenders.
    Lenders use this data to assess creditworthiness and default risk.
    """)

    st.markdown("**Major Credit Bureaus in India:**")
    st.markdown("""
    - TransUnion CIBIL
    - Experian India
    - Equifax India
    - CRIF High Mark
    """)


def credit_bureau_data_tables():
    st.subheader("2️⃣ Data Received from Credit Bureau")

    st.markdown("### 📊 Credit Bureau Data Categories")

    table_1 = pd.DataFrame({
        "Category": [
            "Identity & Demographics",
            "Trade Line Data",
            "Repayment History"
        ],
        "Variables": [
            "Name, DOB, PAN, Address history",
            "Loan type, loan amount, outstanding, EMI, tenure, account status",
            "Monthly DPD grid (000, 030, 060, 090+), worst DPD"
        ]
    })

    table_2 = pd.DataFrame({
        "Category": [
            "Enquiry Data",
            "Summary Variables"
        ],
        "Variables": [
            "Number of enquiries, enquiry type, enquiry recency",
            "Credit score, total active loans, credit age, total outstanding"
        ]
    })

    col1, col2 = st.columns(2)
    with col1:
        st.table(table_1)
    with col2:
        st.table(table_2)


def project_overview():
    st.subheader("3️⃣ Project: Credit Default Prediction Using Bureau Data")

    st.markdown("""
    **Dataset Used:** Home Credit Default Risk Dataset (Kaggle)

    This dataset closely resembles real-world credit bureau and underwriting data,
    containing applicant details, bureau trade lines, repayment history, and enquiry proxies.
    """)

def preprocessing_details():
    st.subheader("🔧 Pre-processing & Feature Engineering Steps")

    st.markdown("### Bureau Balance → DPD Feature Engineering")

    st.markdown("""
    **Source Table:** `bureau_balance.csv`
    **Raw Variable Used:** `STATUS`

    **Transformation Applied:**
    - Converted categorical DPD status into numeric delinquency days (`DPD`)
    - Mapped values such as `000 → 0`, `030 → 30`, `060 → 60`, `090 → 90+`

    **Derived Variables:**
    - `max_dpd_ever` → Maximum delinquency observed across history
    - `cnt_30plus` → Total count of 30+ DPD occurrences
    - `recent_6m_30plus` → Count of 30+ DPD in last 6 months (recency indicator)
    """)

    st.markdown("---")

    st.markdown("### Bureau Trade-line Aggregation")

    st.markdown("""
    **Source Table:** `bureau.csv`
    **Key Identifier:** `SK_ID_CURR`

    **Variables Aggregated:**
    - `total_loans` → Count of all credit trade-lines
    - `active_loans` → Count of currently active loans (`CREDIT_ACTIVE`)
    - `total_outstanding` → Sum of outstanding balances (`AMT_CREDIT_SUM_DEBT`)
    - `unsecured_cnt` → Count of unsecured loans (`CREDIT_TYPE`)
    - `max_dpd_ever` → Worst delinquency across all loans
    - `cnt_30plus` → Total delinquency count
    - `recent_6m_30plus` → Recent delinquency intensity
    """)

    st.markdown("---")

    st.markdown("### Enquiry Proxy Feature Creation")

    st.markdown("""
    **Source Table:** `previous_application.csv`

    **Variables Derived:**
    - `enquiry_cnt_6m` → Number of recent loan applications (credit hunger indicator)
    - `refused_cnt` → Count of previously refused applications (`NAME_CONTRACT_STATUS`)
    """)

    st.markdown("---")

    st.markdown("### Missing Value Treatment")

    st.markdown("""
    **Variables Applied To:**
    - All numerical model features including
      `AMT_INCOME_TOTAL`, `AMT_CREDIT`, `total_loans`, `max_dpd_ever`, `enquiry_cnt_6m`, etc.

    **Method Used:**
    - Median imputation for missing values
    - Missing indicator flags created for each variable (e.g., `max_dpd_ever_missing`)

    **Reason:**
    - Missing values in credit data often indicate *New-to-Credit* behavior and carry risk signal
    """)

    st.markdown("---")

    st.markdown("### Capping & Outlier Treatment")

    st.markdown("""
    **Variables Applied To:**
    - `AMT_INCOME_TOTAL`
    - `AMT_CREDIT`
    - `total_outstanding`
    - `enquiry_cnt_6m`
    - `cnt_30plus`

    **Method Used:**
    - Values capped at 1st and 99th percentiles

    **Purpose:**
    - Prevent extreme values from disproportionately influencing the logistic regression model
    - Improve model stability and regulatory acceptability
    """)



def final_feature_list():
    st.subheader("4️⃣ Final Variables Used in Logistic Regression")

    feature_definitions = pd.DataFrame({
        "Variable": [
            "AMT_INCOME_TOTAL",
            "AMT_CREDIT",
            "DAYS_EMPLOYED",
            "total_loans",
            "active_loans",
            "total_outstanding",
            "unsecured_cnt",
            "max_dpd_ever",
            "cnt_30plus",
            "recent_6m_30plus",
            "enquiry_cnt_6m",
            "refused_cnt"
        ],
        "Definition": [
            "Total declared income of the applicant",
            "Loan amount applied for",
            "Employment duration in days",
            "Total number of loans in bureau",
            "Number of currently active loans",
            "Total outstanding amount across loans",
            "Count of unsecured loans",
            "Worst delinquency observed historically",
            "Count of 30+ DPD occurrences",
            "Recent 30+ DPD occurrences in last 6 months",
            "Number of loan enquiries in last 6 months",
            "Count of previously refused loan applications"
        ]
    })

    st.table(feature_definitions)


def train_test_info():
    st.subheader("5️⃣ Dataset Split")

    st.markdown("""
    - **Total records used:** 50,000
    - **Training set:** 37,500 (75%)
    - **Test set:** 12,500 (25%)

    Stratified sampling was used to maintain class balance.
    """)


def model_intro():
    st.subheader("6️⃣ Model Used: Logistic Regression")

    st.markdown("""
    Logistic Regression is the most widely used model in lending risk analytics.

    **Why Logistic Regression?**
    - Interpretable and explainable
    - Stable over time
    - Regulator-friendly
    - Easy to translate into scorecards
    """)


def metrics_explanation():
    st.subheader("7️⃣ Model Evaluation Metrics")

    st.markdown("""
    - **Recall:**
      Measures how many actual defaulters the model is able to identify.
      Critical to minimize risk exposure.

    - **Precision:**
      Indicates how many predicted defaulters actually default.
      Important for controlling false rejections.

    - **ROC-AUC:**
      Measures overall ranking power of the model across all cut-offs.

    - **KS Statistic:**
      Captures maximum separation between good and bad borrowers.
      Standard metric in banking risk models.

    - **Weight of Evidence (WOE):**
      Measures predictive strength of individual variables.

    - **Information Value (IV):**
      Quantifies how useful a variable is in distinguishing defaulters from non-defaulters.
    """)

# -----------------------------
# Main App Execution
# -----------------------------

credit_bureau_intro()
credit_bureau_data_tables()
project_overview()
preprocessing_details()
final_feature_list()
train_test_info()
model_intro()
metrics_explanation()
